<?php

namespace App\Services;

use App\Models\Setting;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use RuntimeException;
use ZipArchive;

/**
 * Full-system backup and restore — everything except the code: every table's
 * data, uploaded attachments, and the logo.
 *
 * No mysqldump: this server has no MySQL client tools on its PATH, and even
 * where one exists it is one more thing that has to be present and the right
 * version at restore time, possibly on a different machine. Reading rows
 * through the same DB connection Laravel already has open is portable by
 * construction, so that is what both directions use.
 */
class BackupService
{
    /**
     * Queue/cache bookkeeping — meaningful only to the instance that wrote it.
     * A restored jobs table would replay stale queued work against data that
     * no longer matches it; migrations is regenerated by the app itself and
     * comparing it is how manifest() catches a schema mismatch before restore
     * touches a single row.
     */
    private const SKIP_TABLES = ['jobs', 'job_batches', 'failed_jobs', 'cache', 'cache_locks', 'sessions'];

    public const CONFIRM_PHRASE = 'استرجاع';

    /**
     * Builds the archive on a temp path and hands the path back. Returning a
     * path rather than sending the response is what keeps this a service: it
     * takes and returns data, and it is the controller's job to turn that into
     * an HTTP download (CLAUDE.md § 3) — a service that calls response()->send()
     * cannot be reused from a command or a queued job.
     */
    public function build(): string
    {
        $zip = new ZipArchive();
        $tmpPath = tempnam(sys_get_temp_dir(), 'backup_');

        if ($zip->open($tmpPath, ZipArchive::CREATE | ZipArchive::OVERWRITE) !== true) {
            throw new RuntimeException('مقدرش أفتح ملف مؤقت للباك أب.');
        }

        $tables = $this->backupableTables();

        $zip->addFromString('manifest.json', json_encode($this->manifest($tables), JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE));

        foreach ($tables as $table) {
            $rows = DB::table($table)->get()->map(fn ($row) => (array) $row)->all();
            $zip->addFromString("database/{$table}.json", json_encode($rows, JSON_UNESCAPED_UNICODE));
        }

        $this->addDisk($zip, 'local', 'storage/private');
        $this->addDisk($zip, 'public', 'storage/public');

        $zip->close();

        return $tmpPath;
    }

    /** Filename the download should carry. */
    public function filename(): string
    {
        return Str::slug($this->appName()) . '-backup-' . now()->format('Y-m-d-His') . '.zip';
    }

    /**
     * The branded name shown throughout the app (nav, topbar) — an admin can
     * change it from a fixed Laravel default, so it, not config('app.name'),
     * is what both the download filename and the manifest inside it should
     * agree on.
     */
    private function appName(): string
    {
        return Setting::get('app_name') ?? config('app.name');
    }

    /**
     * @return array{app_name: string, created_at: string, tables: array<string, int>}
     */
    private function manifest(array $tables): array
    {
        return [
            'app_name' => $this->appName(),
            'created_at' => now()->toIso8601String(),
            // column count per table, not just the name — catches a schema that
            // has since gained or lost a column, which a restore must refuse
            // rather than silently write partial or misaligned rows.
            'tables' => collect($tables)->mapWithKeys(fn ($t) => [$t => count(Schema::getColumnListing($t))])->all(),
        ];
    }

    /** @return array<int, string> every real table this database has, minus the ones restore must never touch */
    private function backupableTables(): array
    {
        // Both arguments matter and neither is optional in practice.
        //
        // $schema: the DB user this app connects with (root, no password, per
        // .env) can see every database on the MySQL instance, not just this
        // app's. Schema::getTableListing(null, ...) queries information_schema
        // with no schema filter and returns EVERY table on the whole server —
        // confirmed while testing this: it came back with tables from several
        // other unrelated projects sharing the same local MySQL install. A
        // restore built on that list would have wiped tables belonging to
        // other apps entirely. Reading this connection's own configured
        // database name and passing it as $schema scopes the query to it.
        //
        // schemaQualified=false: the default return is "database.table" for
        // MySQL, which neither DB::table() nor Schema::hasTable() accepts.
        $database = config('database.connections.' . config('database.default') . '.database');

        return collect(Schema::getTableListing($database, schemaQualified: false))
            ->reject(fn ($table) => in_array($table, self::SKIP_TABLES, true))
            ->values()
            ->all();
    }

    private function addDisk(ZipArchive $zip, string $disk, string $zipPrefix): void
    {
        $storage = Storage::disk($disk);

        foreach ($storage->allFiles() as $path) {
            $zip->addFile($storage->path($path), "{$zipPrefix}/{$path}");
        }
    }

    /**
     * Opens the upload just far enough to read its manifest — no table is
     * touched — so the controller can show what it would do before anyone
     * commits to overwriting the running system.
     *
     * @return array{app_name: string, created_at: string, tables: array<string, int>}
     */
    public function inspect(string $zipPath): array
    {
        $zip = $this->open($zipPath);
        $manifest = json_decode($zip->getFromName('manifest.json') ?: '', true);
        $zip->close();

        if (! is_array($manifest) || ! isset($manifest['tables'])) {
            throw new RuntimeException('الملف ده مش باك أب صالح — manifest.json ناقص أو تالف.');
        }

        return $manifest;
    }

    /**
     * Wipes every current table this backup covers and replaces its rows
     * wholesale, then replaces the attachment and logo disks the same way.
     * There is no partial mode: a restore is the system on the day the backup
     * was taken, in full, or it does not run at all.
     */
    public function restore(string $zipPath): void
    {
        $zip = $this->open($zipPath);
        $manifest = $this->inspect($zipPath);

        $this->assertCompatible($manifest);

        // FK checks off for the wipe-and-reload rather than working out a safe
        // deletion order: the table list comes from Schema::getTableListing(),
        // which promises nothing about dependency order, and guessing wrong
        // fails the restore partway through with the database in neither its
        // old state nor its new one.
        DB::statement('SET FOREIGN_KEY_CHECKS=0');

        try {
            DB::transaction(function () use ($zip, $manifest) {
                foreach (array_keys($manifest['tables']) as $table) {
                    if (! Schema::hasTable($table)) {
                        continue;
                    }

                    DB::table($table)->delete();

                    $rows = json_decode($zip->getFromName("database/{$table}.json") ?: '[]', true);

                    // chunk: a large table restored as one insert() call risks
                    // the placeholder-count ceiling a single query can hold.
                    foreach (array_chunk($rows, 500) as $chunk) {
                        if ($chunk !== []) {
                            DB::table($table)->insert($chunk);
                        }
                    }
                }
            });
        } finally {
            DB::statement('SET FOREIGN_KEY_CHECKS=1');
        }

        $this->restoreDisk($zip, 'local', 'storage/private');
        $this->restoreDisk($zip, 'public', 'storage/public');

        $zip->close();
    }

    /**
     * Refuses a backup taken against a different shape of database — a
     * missing table or a column count that no longer matches is exactly the
     * situation where blindly inserting rows corrupts the running schema
     * instead of restoring a prior state of it.
     */
    private function assertCompatible(array $manifest): void
    {
        $current = collect($this->backupableTables())
            ->mapWithKeys(fn ($t) => [$t => count(Schema::getColumnListing($t))])
            ->all();

        foreach ($manifest['tables'] as $table => $columnCount) {
            if (! isset($current[$table])) {
                throw new RuntimeException("الباك أب فيه جدول «{$table}» مش موجود في النظام الحالي. النسخة مختلفة عن اللي عندك دلوقتي.");
            }

            if ($current[$table] !== $columnCount) {
                throw new RuntimeException("جدول «{$table}» في الباك أب شكله مختلف عن الحالي — النظام لازم يبقى نفس الإصدار وقت الاسترجاع.");
            }
        }
    }

    private function restoreDisk(ZipArchive $zip, string $disk, string $zipPrefix): void
    {
        $storage = Storage::disk($disk);

        // Wiped before restoring, same as a database table — a leftover file
        // from after the backup was taken has no business surviving a restore
        // to that point.
        foreach ($storage->allFiles() as $path) {
            $storage->delete($path);
        }

        $prefixLen = strlen($zipPrefix) + 1;

        for ($i = 0; $i < $zip->numFiles; $i++) {
            $name = $zip->getNameIndex($i);

            if (! str_starts_with($name, "{$zipPrefix}/") || str_ends_with($name, '/')) {
                continue;
            }

            $storage->put(substr($name, $prefixLen), $zip->getFromIndex($i));
        }
    }

    /**
     * The upload request only filters by extension (`mimes:zip`) — Laravel's
     * rule never reads the bytes. The real check is here, on the file
     * ZipArchive is about to open (CLAUDE.md § 5).
     */
    private function open(string $zipPath): ZipArchive
    {
        $mime = (new \finfo(FILEINFO_MIME_TYPE))->file($zipPath);

        if (! in_array($mime, ['application/zip', 'application/x-zip-compressed'], true)) {
            throw new RuntimeException("الملف ده مش zip حقيقي (النوع الفعلي: {$mime}).");
        }

        $zip = new ZipArchive();

        if ($zip->open($zipPath) !== true) {
            throw new RuntimeException('الملف مش zip صالح.');
        }

        return $zip;
    }
}
